baseurl: "https://keichi.dev/"
title: "Keichi Takahashi"
copyright: "&copy; 2019&ndash;2023 Keichi Takahashi"
theme: literati
defaultContentLanguage: ja
disableHugoGeneratorInject: true
hasCJKLanguage: true
enableGitInfo: true
pygmentsCodefences: true
pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: About
      identifier: about
      url: /
    - name: CV
      identifier: cv
      url: https://s3-ap-northeast-1.amazonaws.com/keichi.net/cv_takahashi.pdf
    - name: Blog
      identifier: blog
      url: /post/

params:
  author: Keichi Takahashi
  email: keichi.t@me.com
  twitter: _keichi_
  github: keichi
